- name: delete apt cache
  become: true
  become_user: root
  become_method: su
  command: rm -vf /var/lib/apt/lists/*

- name: install requirement dpkg to install php5
  become: true
  become_user: root
  become_method: su
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - ca-certificates
    - apt-transport-https
    - wget
    - curl
    - python-apt
    - software-properties-common
    - git

- name: Add key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present

- name: Add Php Repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ stretch main"
    state: present
    filename: php.list
    update_cache: true

- name: wget repository php
  shell: wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

- name: add repository php
  shell: echo 'deb https://packages.sury.org/php/ $(lsb_release -sc) main' | tee /etc/apt/sources.list.d/php.list

- name: wget repository
  shell: wget https://files.phpmyadmin.net/phpMyAdmin/5.1.1/phpMyAdmin-5.1.1-all-languages.tar.gz

- name: tar phpmyadmin
  shell: tar -zxvf phpMyAdmin-5.1.1-all-languages.tar.gz

- name: move phpmyadmin
  shell: mv phpMyAdmin-5.1.1-all-languages /usr/share/phpMyAdmin

- name: apt update
  shell: apt update

- name: Copy lxc_mariadb.conf
  template:
    src: templates/lxc_mariadb.conf
    dest: /etc/nginx/sites-available/{{ domain }}
  vars:
    servername: "{{ domain }}"

- name: Symlink lxc_mariadb.conf
  command: ln -sfn /etc/nginx/sites-available/{{ domain }} /etc/nginx/sites-enabled/{{ domain }}
  notify:
    - restart nginx

- name: Write {{ domain }} to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^.*{{ domain }}$"
    line: "127.0.0.1 {{ domain }}"
    state: present
