- name: stop apache2
  become: true
  become_user: root
  become_method: su
  action: service name=apache2 state=stopped

- name: restart nginx
  become: true
  become_user: root
  become_method: su
  action: service name=nginx state=restarted

- name: restart php
  become: true
  become_user: root
  become_method: su
  action: service name=php7.2-fpm state=restarted
